-- 1
CREATE TABLE ROLES (
    ID INT GENERATED ALWAYS AS IDENTITY,
    ROLE VARCHAR(1000),
    CONSTRAINT ROLES_PK PRIMARY KEY (ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 2
-- CREATE TABLE COUNTRIES(
--     ID INT GENERATED ALWAYS AS IDENTITY,
--   COUNTRY VARCHAR(50),
--   COUNTRY_CODE VARCHAR(8) UNIQUE NOT NULL,
--   CONSTRAINT COUNTRIES_PK PRIMARY KEY (ID),
--   ADDED_TIME TIMESTAMP DEFAULT now()
-- );

-- 3
CREATE TABLE USERS (
    ID INT GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(1000) NOT NULL,
    LAST_NAME VARCHAR(1000) NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    ROLE_ID INT NOT NULL , -- FK
    CONTACT_NO VARCHAR(11) NOT NULL UNIQUE,
    EMERGENCY_CONTACT_NO VARCHAR(11) NOT NULL  UNIQUE,
    BIRTH_DATE DATE NOT NULL ,
    PERMANENT_ADDRESS TEXT NOT NULL,
    -- COUNTRY_ID INT NOT NULL, -- FK
    PASSPORT_ID VARCHAR(15) UNIQUE,


    CONSTRAINT USERS_PK PRIMARY KEY (ID),
    CONSTRAINT EMAIL_FORMAT_CHECK
    CHECK (EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT USERS_CONTACT_NO_CHECK
    CHECK (CONTACT_NO ~ '^\+?\d{10,15}$'),
    CONSTRAINT USERS_EMERGENCY_CONTACT_NO CHECK ( EMERGENCY_CONTACT_NO ~ '^\+?\d{10,15}$' ),
    CONSTRAINT USERS_ROLE_FK
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES(ID),
    -- CONSTRAINT USERS_COUNTRY_FK FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 4
CREATE TABLE ROOM_TYPES(
    ID INT GENERATED ALWAYS AS IDENTITY,
    ROOM_TYPE VARCHAR(15),
    CONSTRAINT ROOM_TYPES_PK PRIMARY KEY (ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 5
CREATE TABLE FLOORS(
    ID INT GENERATED ALWAYS AS IDENTITY,
    FLOOR_NO INT,
    CONSTRAINT FLOORS_PK PRIMARY KEY (ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 6
CREATE TABLE ROOMS(
    ID INT GENERATED ALWAYS AS IDENTITY,
    ROOM_TYPE_ID INT NOT NULL,
    FLOOR_NO_ID INT NOT NULL,
    PER_DAY_RENT_FEE FLOAT,
    CONSTRAINT ROOMS_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_ROOMS_TYPES_FK FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPES(ID) ,
    CONSTRAINT USERS_FLOOR_NO_FK FOREIGN KEY (FLOOR_NO_ID) REFERENCES FLOORS(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 7
CREATE TABLE ROOM_RENT_INFORMATION(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT NOT NULL ,
    ROOM_ID INT NOT NULL ,
    ROOM_RENT_DAYS INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    MEAL_STATUS BOOLEAN DEFAULT(TRUE),
    TOTAL_MEAL_COUNT INT DEFAULT(0),
    USED_MEAL_COUNT INT DEFAULT (0),
    LIFETIME_USED_MEAL_TOKEN INT DEFAULT (0),
    CONSTRAINT ROOM_RENT_INFORMATION_PK PRIMARY KEY (ID),
    CONSTRAINT ROOM_RENT_INFORMATION_USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT ROOM_RENT_INFORMATION_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);


CREATE TYPE TRANSACTION_TYPE AS ENUM ('DEBIT', 'CREDIT');
CREATE TYPE PAYMENT_METHOD  AS ENUM ('BKASH', 'NAGAD','ROCKET','ONLINE','OFFLINE');
CREATE TYPE PAYMENT_FOR AS ENUM ('PAYMENT FOR ROOM RENT','PAYMENT FOR MEAL TOKEN');

-- 8
CREATE TABLE TRANSACTIONS(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT, --FK
    ROOM_NO INT, --FK
    PAYMENT_DATE DATE NOT NULL,
--     START_DATE DATE NOT NULL,
--     END_DATE DATE NOT NULL,
--     TOTAL_AMOUNT FLOAT,
--     PAID_AMOUNT FLOAT,
    PAYMENT_METHOD PAYMENT_METHOD NOT NULL,
    TRANSACTION_TYPE TRANSACTION_TYPE NOT NULL,
    PAYMENT_FOR PAYMENT_FOR NOT NULL,
    CONSTRAINT TRANSACTIONS_PK PRIMARY KEY (ID),
    CONSTRAINT TRANSACTIONS_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT TRANSACTIONS_FK_ROOM_NO FOREIGN KEY (ROOM_NO) REFERENCES ROOMS(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 9
CREATE TABLE ROOM_RENT_HISTORY(
    ID INT GENERATED ALWAYS AS IDENTITY,
    CONSTRAINT ROOM_RENT_HISTORY_PK PRIMARY KEY (ID),
    USER_ID INT,
    CONSTRAINT ROOM_RENT_HISTORY_FK1 FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    TRANSACTION_ID INT,
    CONSTRAINT ROOM_RENT_HISTORY_FK2 FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(ID),
    ROOM_ID INT NOT NULL,
    CONSTRAINT ROOM_RENT_HISTORY_FK3 FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID),
    START_TIME DATE,
    END_TIME DATE,
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 10
CREATE TABLE MEAL_TOKEN_HISTORY(
    ID INT GENERATED ALWAYS AS IDENTITY,
    CONSTRAINT MEAL_TOKEN_HISTORY_PK PRIMARY KEY (ID),
    USER_ID INT,
    CONSTRAINT MEAL_TOKEN_HISTORY_FK1 FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    ROOM_ID INT,
    CONSTRAINT MEAL_TOKEN_HISTORY_FK2 FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID),
    TRANSACTION_ID INT,
    CONSTRAINT MEAL_TOKEN_HISTORY_FK23 FOREIGN KEY(TRANSACTION_ID) REFERENCES TRANSACTIONS(ID),
    TOKEN_AMOUNT INT NOT NULL ,
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 11
CREATE TABLE COMPLAINT_STATUS(
    ID INT GENERATED ALWAYS AS IDENTITY,
    STATUS VARCHAR(20) UNIQUE NOT NULL ,
    CONSTRAINT COMPLAINT_STATUS_PK PRIMARY KEY (ID),
    ADDED_BY_ID INT,
    CONSTRAINT COMPLAINT_STATUS_ADDED_BY_ID_FK FOREIGN KEY(ADDED_BY_ID) REFERENCES USERS(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

--12
CREATE TABLE COMPLAINT(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    DESCRIPTION TEXT,
    COMPLAINT_STATUS INT NOT NULL,
    COMPLAINT_DATE TIMESTAMP DEFAULT now(),
    CONSTRAINT COMPLAINTS_PK PRIMARY KEY (ID),
    CONSTRAINT COMPLAINTS_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT COMPLAINT_ROOM_ID_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOMS(ID),
    CONSTRAINT COMPLAINT_COMPLAINT_STATUS_FK FOREIGN KEY (ID) REFERENCES COMPLAINT_STATUS(ID)
);

--13
CREATE TABLE REVIEWS(
    ID INT GENERATED ALWAYS AS  IDENTITY,
    USER_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    DESCRIPTION TEXT,
    REVIEW_DATE TIMESTAMP DEFAULT now(),
    CONSTRAINT REVIEW_PK PRIMARY KEY (ID),
    CONSTRAINT REVIEW_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT REVIEW_ROOM_ID_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOMS(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 14
CREATE TABLE DISCUSSION(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT NOT NULL ,
    CONSTRAINT DISCUSSIONS_PK PRIMARY KEY(ID),
    CONSTRAINT DISCUSSION_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    DESCRIPTION TEXT,
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 15
CREATE TABLE COMMENTS(
    ID INT GENERATED ALWAYS AS  IDENTITY ,
    CONSTRAINT COMMENT_PK PRIMARY KEY (ID),
    USER_ID INT NOT NULL ,
    CONSTRAINT COMMENT_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    COMMENT TEXT,
    COMMENT_DATE TIMESTAMP DEFAULT now(),
    DISCUSSION_ID INT NOT NULL ,
    CONSTRAINT COMMENTS_DISCUSSION_ID FOREIGN KEY (DISCUSSION_ID) REFERENCES DISCUSSION(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

CREATE TYPE DAYS_ AS ENUM ('SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY');


-- 16
CREATE TABLE MEAL_TYPES( -- BREAKFAST,DINNER,LUNCK,SNACKS
    ID INT GENERATED ALWAYS AS IDENTITY,
    MEAL_TYPE VARCHAR(50),
    ADDED_BY_ID INT,
    ADDED_DATE TIMESTAMP DEFAULT now(),
    CONSTRAINT MEAL_TYPES_PK PRIMARY KEY (ID),
    CONSTRAINT MEAL_TYPES_ADDED_BY_ID_FK FOREIGN KEY (ADDED_BY_ID) REFERENCES USERS(ID)
);


-- 17
CREATE TABLE MENU_ITEMS( -- EGG CURRY, RICE, LENTILS
    ID INT GENERATED ALWAYS AS IDENTITY,
    ITEM_NAME VARCHAR(100) NOT NULL ,
    DESCRIPTION TEXT NOT NULL ,
    IS_VEG BOOLEAN NOT NULL,
    ADDED_BY_ID INT,
    CONSTRAINT MENU_ITEMS_PK PRIMARY KEY (ID),
    CONSTRAINT MENU_ITEM_ADDED_BY_FK FOREIGN KEY (ADDED_BY_ID) REFERENCES USERS(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

--18
CREATE TABLE MENUS( --SATURDAY MENU, SUNDAY MENU, MONDAY MENU
    ID INT GENERATED ALWAYS AS  IDENTITY,
    DAYS__ DAYS_ NOT NULL,
    ADDED_BY INT NOT NULL,
    CONSTRAINT MENU_PK PRIMARY KEY (ID),
    CONSTRAINT MENU_DAYS_FK FOREIGN KEY (ADDED_BY) REFERENCES USERS(ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);

-- 19
CREATE TABLE MEAL_ITEMS(
    ID INT GENERATED ALWAYS AS  IDENTITY,
    CONSTRAINT MEAL_ITEMS_PK PRIMARY KEY (ID),
    MENU_ITEM_ID INT NOT NULL,
    CONSTRAINT MEAL_ITEM_FK1 FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS(ID),
    MENU_ID INT NOT NULL,
    CONSTRAINT MEAL_ITEM_FK2 FOREIGN KEY (MENU_ID) REFERENCES MENUS(ID),
    MEAL_TYPE_ID INT NOT NULL,
    CONSTRAINT MEAL_ITEM_FK3 FOREIGN KEY (MEAL_TYPE_ID) REFERENCES MEAL_TYPES(ID),
    ADDED_BY INT NOT NULL,
    CONSTRAINT MEAL_ITEM_FK4 FOREIGN KEY (ADDED_BY) REFERENCES USERS(ID),
    CONSTRAINT MEAL_ITEM_PK UNIQUE(MENU_ID,MENU_ITEM_ID),
    ADDED_TIME TIMESTAMP DEFAULT now()
);


-- 20
CREATE TABLE USER_MEAL_HISTORY(
     ID INT GENERATED ALWAYS AS  IDENTITY,
     CONSTRAINT USER_MEAL_HISTORY_PK PRIMARY KEY (ID),
     USER_ID INT NOT NULL,
     CONSTRAINT USER_MEAL_HISTORY_FK1 FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
     USED_TOKEN INT NOT NULL,
     MEAL_ITEM_ID INT,
     CONSTRAINT USER_MEAL_HISTORY_FK2 FOREIGN KEY (MEAL_ITEM_ID) REFERENCES MEAL_ITEMS(ID),
     ADDED_TIME TIMESTAMP DEFAULT now()
);
