spring.application.name=backend
server.address=0.0.0.0
server.port=8000
# spring.datasource.url=jdbc:postgresql://Postgres-net-1:5432/smart_hostel_management
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_hostel_management
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password
spring.servlet.multipart.enabled=true
spring.jpa.hibernate.ddl-auto=create
springdoc.swagger-ui.enabled=true
spring.main.allow-bean-definition-overriding=true

