export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE";
export type EndpointDefinition = {
  id: string;
  category: string;
  title: string;
  description: string;
  method: HttpMethod;
  path: string;
  isPublic?: boolean;
  contentType?: "application/json" | "multipart/form-data";
  defaultPathParams?: Record<string, string>;
  defaultQueryParams?: Record<string, string>;
  bodyTemplate?: unknown;
};

export const ENDPOINTS: EndpointDefinition[] = [
  {
    id: "user-signup",
    category: "Authentication",
    title: "User Signup",
    description: "Register a new user account.",
    method: "POST",
    path: "/user/signup",
    isPublic: true,
    bodyTemplate: { userName: "tenant1", password: "pass1234", role: ["tenant"] },
  },
  {
    id: "user-login",
    category: "Authentication",
    title: "User Login",
    description: "Login and receive JWT token.",
    method: "POST",
    path: "/user/login",
    isPublic: true,
    bodyTemplate: { userName: "tenant1", password: "pass1234" },
  },
  {
    id: "user-upload-image",
    category: "Authentication",
    title: "Upload User Image",
    description: "Upload profile image (multipart/form-data).",
    method: "POST",
    path: "/user/upload-image/{userId}",
    contentType: "multipart/form-data",
    defaultPathParams: { userId: "1" },
  },
  {
    id: "role-get-all",
    category: "Hostel Core",
    title: "Get All Roles",
    description: "Fetch role list.",
    method: "GET",
    path: "/role/get",
  },
  {
    id: "role-get-by-id",
    category: "Hostel Core",
    title: "Get Role By ID",
    description: "Fetch one role by id.",
    method: "GET",
    path: "/role/get/{id}",
    defaultPathParams: { id: "1" },
  },
  {
    id: "role-create",
    category: "Hostel Core",
    title: "Create Role",
    description: "Create a new role.",
    method: "POST",
    path: "/role/create",
    bodyTemplate: { role: "manager" },
  },
  {
    id: "role-update",
    category: "Hostel Core",
    title: "Update Role",
    description: "Update a role by id.",
    method: "PUT",
    path: "/role/update/{roleId}",
    defaultPathParams: { roleId: "1" },
    bodyTemplate: { role: "tenant" },
  },
  {
    id: "role-delete",
    category: "Hostel Core",
    title: "Delete Role",
    description: "Delete a role by id.",
    method: "DELETE",
    path: "/role/delete/{roleId}",
    defaultPathParams: { roleId: "1" },
  },
  {
    id: "floor-create",
    category: "Hostel Core",
    title: "Create Floor",
    description: "Create floor record.",
    method: "POST",
    path: "/floor/create",
    bodyTemplate: { floorNo: 1 },
  },
  {
    id: "floor-get-all",
    category: "Hostel Core",
    title: "Get Floors",
    description: "Fetch all floors.",
    method: "GET",
    path: "/floor",
  },
  {
    id: "floor-get-by-id",
    category: "Hostel Core",
    title: "Get Floor By ID",
    description: "Fetch floor by id.",
    method: "GET",
    path: "/floor/{floorId}",
    defaultPathParams: { floorId: "1" },
  },
  {
    id: "floor-delete",
    category: "Hostel Core",
    title: "Delete Floor",
    description: "Delete floor by id.",
    method: "DELETE",
    path: "/floor/delete/{floorId}",
    defaultPathParams: { floorId: "1" },
  },
  {
    id: "room-create",
    category: "Hostel Core",
    title: "Create Room",
    description: "Create room record.",
    method: "POST",
    path: "/room/create",
    bodyTemplate: { roomNo: 101, roomType: "SINGLE", floorNo: 1, perDayRentFee: 450 },
  },
  {
    id: "room-get-all",
    category: "Hostel Core",
    title: "Get Rooms",
    description: "Fetch all rooms.",
    method: "GET",
    path: "/room",
  },
  {
    id: "room-get-by-id",
    category: "Hostel Core",
    title: "Get Room By ID",
    description: "Fetch room by room id.",
    method: "GET",
    path: "/room/roomId/{roomId}",
    defaultPathParams: { roomId: "1" },
  },
  {
    id: "room-get-by-room-no",
    category: "Hostel Core",
    title: "Get Room By Number",
    description: "Fetch room by room number.",
    method: "GET",
    path: "/room/roomNo/{roomNo}",
    defaultPathParams: { roomNo: "101" },
  },
  {
    id: "room-get-by-type",
    category: "Hostel Core",
    title: "Get Rooms By Type",
    description: "Fetch rooms by roomType query.",
    method: "GET",
    path: "/room/roomType",
    defaultQueryParams: { roomType: "SINGLE" },
  },
  {
    id: "room-update",
    category: "Hostel Core",
    title: "Update Room",
    description: "Update room by id.",
    method: "PUT",
    path: "/room/update/{roomId}",
    defaultPathParams: { roomId: "1" },
    bodyTemplate: { roomNo: 101, roomType: "SINGLE", floorNo: 1, perDayRentFee: 500 },
  },
  {
    id: "room-delete",
    category: "Hostel Core",
    title: "Delete Room",
    description: "Delete room by id.",
    method: "DELETE",
    path: "/room/delete/{roomId}",
    defaultPathParams: { roomId: "1" },
  },
  {
    id: "room-type-create",
    category: "Hostel Core",
    title: "Create Room Type",
    description: "Create room type.",
    method: "POST",
    path: "/room-type/create",
    bodyTemplate: { roomType: "SINGLE" },
  },
  {
    id: "room-type-get-all",
    category: "Hostel Core",
    title: "Get Room Types",
    description: "Fetch room type list.",
    method: "GET",
    path: "/room-type",
  },
  {
    id: "room-type-get-by-name",
    category: "Hostel Core",
    title: "Get Room Type By Name",
    description: "Fetch room type by text value.",
    method: "GET",
    path: "/room-type/roomType/{roomType}",
    defaultPathParams: { roomType: "SINGLE" },
  },
  {
    id: "room-type-get-by-id",
    category: "Hostel Core",
    title: "Get Room Type By ID",
    description: "Fetch room type by id.",
    method: "GET",
    path: "/room-type/id/{roomTypeId}",
    defaultPathParams: { roomTypeId: "1" },
  },
  {
    id: "room-type-update",
    category: "Hostel Core",
    title: "Update Room Type",
    description: "Update room type by id.",
    method: "PUT",
    path: "/room-type/update/{roomTypeId}",
    defaultPathParams: { roomTypeId: "1" },
    bodyTemplate: { roomType: "DELUXE" },
  },
  {
    id: "room-type-delete",
    category: "Hostel Core",
    title: "Delete Room Type",
    description: "Delete room type by id.",
    method: "DELETE",
    path: "/room-type/delete/{roomTypeId}",
    defaultPathParams: { roomTypeId: "1" },
  },
  {
    id: "meal-type-create",
    category: "Food & Menu",
    title: "Create Meal Type",
    description: "Create meal type.",
    method: "POST",
    path: "/mealType/create",
    bodyTemplate: { mealType: "BREAKFAST" },
  },
  {
    id: "meal-type-get-all",
    category: "Food & Menu",
    title: "Get Meal Types",
    description: "Fetch meal types.",
    method: "GET",
    path: "/mealType/get",
  },
  {
    id: "meal-type-get-by-id",
    category: "Food & Menu",
    title: "Get Meal Type By ID",
    description: "Fetch meal type by id.",
    method: "GET",
    path: "/mealType/get/{mealTypeId}",
    defaultPathParams: { mealTypeId: "1" },
  },
  {
    id: "meal-type-update",
    category: "Food & Menu",
    title: "Update Meal Type",
    description: "Update meal type by id.",
    method: "PUT",
    path: "/mealType/update/{mealTypeId}",
    defaultPathParams: { mealTypeId: "1" },
    bodyTemplate: { mealType: "DINNER" },
  },
  {
    id: "meal-type-delete",
    category: "Food & Menu",
    title: "Delete Meal Type",
    description: "Delete meal type by id.",
    method: "DELETE",
    path: "/mealType/delete/{mealTypeId}",
    defaultPathParams: { mealTypeId: "1" },
  },
  {
    id: "menu-item-create",
    category: "Food & Menu",
    title: "Create Menu Item",
    description: "Create menu item.",
    method: "POST",
    path: "/menuItem/create",
    bodyTemplate: { itemName: "Rice", description: "Steamed rice" },
  },
  {
    id: "menu-item-get-all",
    category: "Food & Menu",
    title: "Get Menu Items",
    description: "Fetch menu items.",
    method: "GET",
    path: "/menuItem/get",
  },
  {
    id: "menu-item-get-by-id",
    category: "Food & Menu",
    title: "Get Menu Item By ID",
    description: "Fetch menu item by id.",
    method: "GET",
    path: "/menuItem/get/{menuItemId}",
    defaultPathParams: { menuItemId: "1" },
  },
  {
    id: "menu-item-update",
    category: "Food & Menu",
    title: "Update Menu Item",
    description: "Update menu item by id.",
    method: "PUT",
    path: "/menuItem/update/{menuItemId}",
    defaultPathParams: { menuItemId: "1" },
    bodyTemplate: { itemName: "Rice", description: "Updated description" },
  },
  {
    id: "menu-item-delete",
    category: "Food & Menu",
    title: "Delete Menu Item",
    description: "Delete menu item by id.",
    method: "DELETE",
    path: "/menuItem/delete/{menuItemId}",
    defaultPathParams: { menuItemId: "1" },
  },
  {
    id: "menu-create",
    category: "Food & Menu",
    title: "Create Menu",
    description: "Create menu by day and meal type.",
    method: "POST",
    path: "/menu/create",
    bodyTemplate: { day: "SUNDAY", mealType: "BREAKFAST", menuItems: ["Rice"] },
  },
  {
    id: "menu-get-all",
    category: "Food & Menu",
    title: "Get Menus",
    description: "Fetch all menus.",
    method: "GET",
    path: "/menu/get",
  },
  {
    id: "menu-get-by-id",
    category: "Food & Menu",
    title: "Get Menu By ID",
    description: "Fetch menu by id.",
    method: "GET",
    path: "/menu/get/{menuId}",
    defaultPathParams: { menuId: "1" },
  },
  {
    id: "menu-update",
    category: "Food & Menu",
    title: "Update Menu",
    description: "Update menu by id.",
    method: "PUT",
    path: "/menu/update/{menuId}",
    defaultPathParams: { menuId: "1" },
    bodyTemplate: { day: "MONDAY", mealType: "DINNER", menuItems: ["Rice", "Dal"] },
  },
  {
    id: "menu-delete",
    category: "Food & Menu",
    title: "Delete Menu",
    description: "Delete menu by id.",
    method: "DELETE",
    path: "/menu/delete/{menuId}",
    defaultPathParams: { menuId: "1" },
  },
  {
    id: "comment-get-all",
    category: "Community",
    title: "Get Comments",
    description: "Fetch all comments.",
    method: "GET",
    path: "/comment/get/all",
  },
  {
    id: "comment-get-by-id",
    category: "Community",
    title: "Get Comment By ID",
    description: "Fetch comment by id.",
    method: "GET",
    path: "/comment/get/{id}",
    defaultPathParams: { id: "1" },
  },
  {
    id: "comment-create",
    category: "Community",
    title: "Create Comment",
    description: "Create comment for room and user.",
    method: "POST",
    path: "/comment/create",
    bodyTemplate: { comment: "Great room", userId: 1, roomNo: 101 },
  },
  {
    id: "discussion-get-all",
    category: "Community",
    title: "Get Discussions",
    description: "Fetch all discussions.",
    method: "GET",
    path: "/discussion/get/all",
  },
  {
    id: "discussion-create",
    category: "Community",
    title: "Create Discussion",
    description: "Create new discussion.",
    method: "POST",
    path: "/discussion/create",
    bodyTemplate: { description: "Need maintenance", roomNo: 101, userId: 1 },
  },
  {
    id: "payment-method-get-all",
    category: "Payments & Finance",
    title: "Get Payment Methods",
    description: "Fetch payment methods.",
    method: "GET",
    path: "/payment-method/get",
  },
  {
    id: "payment-method-get-by-name",
    category: "Payments & Finance",
    title: "Get Payment Method By Name",
    description: "Fetch payment method by text.",
    method: "GET",
    path: "/payment-method/get/{paymentMethod}",
    defaultPathParams: { paymentMethod: "CASH" },
  },
  {
    id: "payment-purpose-get-all",
    category: "Payments & Finance",
    title: "Get Payment Purposes",
    description: "Fetch payment purposes.",
    method: "GET",
    path: "/payment-purpose/get",
  },
  {
    id: "payment-purpose-get-by-id",
    category: "Payments & Finance",
    title: "Get Payment Purpose By ID",
    description: "Fetch payment purpose by id.",
    method: "GET",
    path: "/payment-purpose/get/{paymentPurposeId}",
    defaultPathParams: { paymentPurposeId: "1" },
  },
  {
    id: "transaction-type-get-all",
    category: "Payments & Finance",
    title: "Get Transaction Types",
    description: "Fetch transaction types.",
    method: "GET",
    path: "/transaction-type/get",
  },
  {
    id: "transaction-type-get-by-name",
    category: "Payments & Finance",
    title: "Get Transaction Type By Name",
    description: "Fetch transaction type by text.",
    method: "GET",
    path: "/transaction-type/get/{transactionType}",
    defaultPathParams: { transactionType: "CREDIT" },
  },
  {
    id: "room-rent-info-get-all",
    category: "Reports",
    title: "Get Room Rent Information",
    description: "Fetch all room rent information.",
    method: "GET",
    path: "/room-rent-information/get",
  },
  {
    id: "room-rent-info-get-by-username",
    category: "Reports",
    title: "Get Room Rent By User",
    description: "Fetch room rent information by userName.",
    method: "GET",
    path: "/room-rent-information/get/{userName}",
    defaultPathParams: { userName: "tenant1" },
  },
  {
    id: "test-get",
    category: "Testing",
    title: "Test GET",
    description: "Echo test endpoint (secured).",
    method: "GET",
    path: "/test/get/{query}",
    defaultPathParams: { query: "hello" },
  },
  {
    id: "test-post",
    category: "Testing",
    title: "Test POST",
    description: "Echo test endpoint (secured).",
    method: "POST",
    path: "/test/post/{query}",
    defaultPathParams: { query: "hello" },
  },
];
